%% |amo| documentation 
% |amo| computes a version of the Atlantic Multidecadal Oscillation index. 
%
% <CDT_Contents.html Back to Climate Data Tools Contents>
% 
%% Syntax 
% 
%  idx = amo(sst,t) 
%  idx = amo(sst,t,lat,lon)
%
%% Description 
% 
% |idx = amo(sst,t)| calculates AMO index from a time series of 
% sea surface temperatures sst and their corresponding times |t|. 
% |sst| can be a vector of sea surface temperatures that have been
% averaged over a region of interest, or |sst| can be a 3D matrix whose third
% dimension correponds to times |t|. If |sst| is a 3D matrix, a time series is
% automatically generated by averaging all the grid cells in |sst| for each
% time step. Usually, the AMO is calculated from the area-weighted average
% of ssts in the northern Atlantic from 0-70ºN.
%
% |idx = amo(sst,t,lat,lon)| calculates the AMO index for 3D |sst| time
% series and corresponding grid coordinates |lat|,|lon|. Using this syntax,
% grid cells within the AMO region are automatically determined and
% the AMO index is calculated from the area-averaged time series of ssts
% within that region. 

%% Example
% In this example, we will calculate the AMO index using the monthly
% north_atlantic_sst.mat dataset that comes with CDT. Start by loading the data
% that comes with CDT. 

% This dataset contains monthly SST from 1870-2017 for the Northern
% Atlantic region (0-70N)

load north_atlantic_sst.mat

% Get 2D grids from lat,lon arrays: 
[Lon,Lat] = meshgrid(lon,lat);

% This should provide recognizable map: 
pcolor(Lon,Lat,mean(na_sst,3))

%%


%% Calculate the AMO Index

idx = amo(na_sst,t,Lat,Lon); 

%% Plot it up real nice
% With that, we can now plot the AMO timeseries and a 121-month moving
% average as recommended by NOAA <here
% https://www.esrl.noaa.gov/psd/data/timeseries/AMO/>

figure
anomaly(datenum(t),idx); hold on;
plot(t,movmean(idx,121),'-','color',rgb('black'),'linewidth',3);
axis tight
hline(0,'k') % places a horizontal line at 0
datetick('x','keeplimits')
ylabel 'AMO SST anomaly (\circC)'

%% 

load atlantic_sst.mat

sst(abs(sst)>100) = NaN; 
sst = permute(sst,[2 1 3]);
[Lat,Lon] = cdtgrid;
A = cdtarea(Lat,Lon);

idx = amo(sst,t,Lat,Lon); 

figure
subplot(2,1,1) 
anomaly(datenum(t),movmean(idx,121),...
   'topcolor',rgb('orange'),'bottomcolor',rgb('yellow'))
axis tight
datetick('x','keeplimits')


%%


sstd = detrend3(deseason(sst,t));

[C,P] = corr3(sstd,idx);

[Latr,Lonr,Cr,Pr] = recenter(Lat,Lon,C,P,'center',180);

subplot(2,1,2)
imagescn(Lonr,Latr,Cr);
ylim([-40 65])
caxis([-1 1])
cmocean bal
hold on
contour(Lonr,Latr,Cr,[0 0],'k-')
set(gca,'color','k') 


%% Reference
% 
% Enfield, D.B., A.M. Mestas-Nunez, and P.J. Trimble, 2001: The 
% Atlantic Multidecadal Oscillation and its relationship to rainfall and 
% river flows in the continental U.S., Geophys. Res. Lett., 28: 2077-2080.
% <https://doi.org/10.1029/2000GL012745 doi:0.1029/2000GL012745>
% 
%% Author Info
% This function was written by Kaustubh Thirumalai of the University of 
% Arizona, March 2019.
% <http://www.kaustubh.info>
